INSERT INTO [CBRM].[dbo].[LamsLoanInfoTemp] (
    [relNo],
    [llid],
    [facilityNoLOAN],
    [tenure],
    [lastSanctionLimit],
    [sanctionLimit],
    [sanctionDate],
    [emiAmount],
    [emi1stDate],
    [emiLastDate],
    [statusLOAN],
    [loanExpiryDate],
    [branchCode],
    [referralCode],
    [limitInWords],
    [linkAC],
    [tOSDDOCRecieeveDate],
    [channelRemarks],
    [relationshipNumber],
    [fundTransferAmount],
    [intRateWavedBy],
    [legalDate],
    [mCCURemarks],
    [interestType],
    [remarksLOAN],
    [banca],
    [refundBanca],
    [securityCode],
    [ftpRate],
    [interestRate],
    [oldReferenceNO],
    [numberOfPDCrecieved],
    [disCode],
    [pdcBank],
    [pOAmount],
    [dLACode],
    [pdcBranch],
    [empRerefence],
    [dateJoin],
    [collectionData],
    [engineNo],
    [carModel],
    [carDetails],
    [regNo],
    [processingFeeWavedBy],
    [poBenificiary],
    [chasisNo],
    [vendorName],
    [vendorAddress],
    [carStatus],
    [odAC],
    [odExpireDate],
    [udcValue],
    [odLimit],
    [director],
    [directorCompany],
    [odLoanCategory],
    [collectionDate],
    [item],
    [tabStatus],
    [wavedBy],
    [netAmount],
    [grossAmount],
    [purpose],
    [rowId],
    [bftn],
    [pdc],
    [si],
    [bftnAccount],
    [status],
    [routingNo],
    [segmentCode],
    [actionStatus],
    [segment],
    [loanAccountNo]
)
SELECT
    NULL,
    L.[lonLLID],
    L.[lonFacilityNo],
    CONVERT(varchar, L.[lonTenor]),
    CONVERT(varchar, L.[lonLastSanctionLimit]),
    CONVERT(varchar, L.[lonSanctionLimit]),
    CONVERT(varchar, L.[lonSanctionDate], 103),
    CONVERT(varchar, L.[lonEMI]),
	CONVERT(varchar, L.[lonEMI1stDate], 103) AS emi1stDate,
    CONVERT(varchar, L.[lonEMILastDate], 103),
    L.[lonStatus],
	CONVERT(varchar, L.[lonExpiryDate], 103) AS loanExpiryDate,
    CONVERT(varchar, L.[lonBranchNo]),
    L.[lonReferralCode],
    L.[lonLimitInWords],
    L.[lonLinkAccNo],
    CONVERT(varchar, L.[lonDocReceiveDate], 103),
    ML.[mglChannelRemarks],
    ML.[mglRelationshipNumber],
    CONVERT(varchar, ML.[mglFundTransferAmount]),
    ML.[mglIntRateWavedBy],
    CONVERT(varchar, ML.[mglLegalDate], 103),
    ML.[mglMCCURemarks],
    ML.[mglInterestType],
    NULL,
    CONVERT(varchar, L.[lonLastBanca]),
    CONVERT(varchar, L.[lonCalculatedBanca]),
    L.[lonSecurityCode],
    L.[lonFTPRate],
    L.[lonInterestRate],
    PL.[prlOldReferenceNo],
    CONVERT(varchar, PL.[prlPDCReceived]),
    COALESCE(PL.[prlDiscCode], AL.[atlDiscCode], SME.[smlDiscCode], CLL.[cllDiscCode]),
    COALESCE(PLB.[bnkName], ALB.[bnkName], SMEB.[bnkName], CLLB.[bnkName]),
    CONVERT(varchar, SME.[smlPOAmount]),
    COALESCE(ML.[mglDLACode], SME.[smlDLACode], CLL.[cllDLACode]),
    COALESCE(ALBR.[brnName], CLLBR.[brnName]),
    AL.[atlEmpReference],
    CONVERT(varchar, AL.[atlDateJoin], 103),
    AL.[atlCollectionData],
    AL.[atlEngineNo],
    AL.[atlModel],
    AL.[atlDetail],
    AL.[atlRegNo],
    AL.[atlProcesingFeeWaivedBy],
    AL.[atlPOBeneficiary],
    AL.[atlChasisNo],
    AL.[atlVendorName],
    AL.[atlVendorAddress],
    AL.[atlCarStatus],
    SME.[smlODAccNo],
    CONVERT(varchar, SME.[smlODExpireDate], 23),
    CONVERT(varchar, SME.[smlUDCValue]),
	SME.[smlODLimit],
	0 AS director,
	COALESCE(PL.[prlDirectorCompany], AL.[atlDirectorCompany], SME.[smlDirectorCompany], CLL.[cllDirectorCompany]),
	SME.[smlODLoanCategory],
	COALESCE(AL.[atlCollectionData], SME.[smlCollectionData], CLL.[cllCollectionData]),
	NULL,
	NULL,
	COALESCE(ML.[mglIntRateWavedBy], AL.[atlProcesingFeeWaivedBy]),
	NULL,
	NULL,
	CLL.[cllPurpose],
	newId(),
	0 AS bftn,
	0 AS pdc,
	0 AS si,
	NULL AS bftnAccount,
	15,
    NULL,
    NULL,
    NULL,
    NULL,
    L.[lonLoanAccNo]
FROM
    IDTP_Report.[dbo].[tbl_App_Loan] L
    LEFT JOIN IDTP_Report.[dbo].[tbl_Lon_PersonalLoan] PL ON L.[lonLLID] = PL.[prlLoanLLID]
    LEFT JOIN IDTP_Report.[dbo].[tbl_Lon_AutoLoan] AL ON L.[lonLLID] = AL.[atlLoanLLID]
    LEFT JOIN IDTP_Report.[dbo].[tbl_Lon_SMELoan] SME ON L.[lonLLID] = SME.[smlLoanLLID]
    LEFT JOIN IDTP_Report.[dbo].[tbl_Lon_MortgageLoan] ML ON L.[lonLLID] = ML.[mglLoanLLID]
    LEFT JOIN IDTP_Report.[dbo].[tbl_Lon_CashLineLoan] CLL ON L.[lonLLID] = CLL.[cllLoanLLID]
    LEFT JOIN IDTP_Report.[dbo].[tbl_Conf_Bank] PLB ON PL.[prlPDCBank] = PLB.[bnkID]
    LEFT JOIN IDTP_Report.[dbo].[tbl_Conf_Bank] ALB ON AL.[atlPDCBank] = ALB.[bnkID]
    LEFT JOIN IDTP_Report.[dbo].[tbl_Conf_Branch] ALBR ON AL.[atlPDCBranch] = ALBR.[brnCode]
    LEFT JOIN IDTP_Report.[dbo].[tbl_Conf_Bank] SMEB ON SME.[smlPDCBank] = SMEB.[bnkID]
    LEFT JOIN IDTP_Report.[dbo].[tbl_Conf_Bank] CLLB ON CLL.[cllPDCBank] = CLLB.[bnkID]
    LEFT JOIN IDTP_Report.[dbo].[tbl_Conf_Branch] CLLBR ON CLL.[cllPDCBranch] = CLLBR.[brnCode]
WHERE
    L.[lonLLID] IS NOT NULL 
	AND L.[lonLLID] IN (
    '1133523',
    '1135324',
    '1131242',
    '1131222',
    '357781',
    '372209',
    '361993',
    '400726',
    '436532',
    '433297',
    '438190',
    '443826',
    '444794'
);

	--select * from [LamsLoanInfoTemp] where llid='1019555'